"""empty message

Revision ID: 6310fb6c48e0
Revises: 
Create Date: 2020-01-19 01:22:01.514992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6310fb6c48e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journey',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_table('photo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=250), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('taken_on', sa.String(length=20), nullable=True),
    sa.Column('journey__id', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['journey__id'], ['journey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_latitude'), 'photo', ['latitude'], unique=False)
    op.create_index(op.f('ix_photo_longitude'), 'photo', ['longitude'], unique=False)
    op.create_index(op.f('ix_photo_url'), 'photo', ['url'], unique=False)
    op.create_table('user_journey',
    sa.Column('user_name', sa.String(length=64), nullable=False),
    sa.Column('journey_id', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['journey_id'], ['journey.id'], ),
    sa.ForeignKeyConstraint(['user_name'], ['user.name'], ),
    sa.PrimaryKeyConstraint('user_name', 'journey_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_journey')
    op.drop_index(op.f('ix_photo_url'), table_name='photo')
    op.drop_index(op.f('ix_photo_longitude'), table_name='photo')
    op.drop_index(op.f('ix_photo_latitude'), table_name='photo')
    op.drop_table('photo')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('journey')
    # ### end Alembic commands ###
